--[[FOR ANY EDITORS!!

Remember that if you're editing these values that

15+ Damage on a weapon will PIERCE through Level 1 Armor (Basic Vest)
20+ Damage on a weapon will PIERCE through Level 2 Armor (Kevlar Vest)
25+ Damage on a weapon will PIERCE through Level 6 Armor (Heavy Body Armor)
35+ Damage on a weapon will PIERCE through Level 3 and 5 Armor (Full Body Armor and Automaton Construct Armor)
100+ Damage on a weapon will PIERCE through Level 4 Armor (Juggernaut Armor)

You can also edit the values above in armors.lua
]]

parse("mp_wpndmg usp 13")
parse("mp_wpndmg glock 11")
parse("mp_wpndmg deagle 36")
parse("mp_wpndmg elite 14")
parse("mp_wpndmg mp5 11")
parse("mp_wpndmg m3 30")
parse("mp_wpndmg xm1014 25")
parse("mp_wpndmg m4a1 19")
parse("mp_wpndmg ak-47 24")
parse("mp_wpndmg p90 14")
parse("mp_wpndmg flamethrower 45")
parse("mp_wpndmg claw 50")
parse("mp_wpndmg machete 99")
parse("mp_wpndmg rocketlauncher 35")
parse("mp_wpndmg grenadelauncher 27")
parse("mp_wpndmg m249 18")
parse("mp_wpndmg m134 21")
parse("mp_wpndmg awp 75")
parse("mp_wpndmg_z1 awp 100")
parse("mp_wpndmg scout 44")
parse("mp_wpndmg_z1 scout 95")
parse("mp_wpndmg rpglauncher 50")
parse("mp_wpndmg ump45 21")
parse("mp_wpndmg gasgrenade 9")
parse("mp_wpndmg knife 65")
parse("mp_wpndmg chainsaw 40")
parse("mp_wpndmg mac10 13")
parse("mp_wpndmg tmp 11")
parse("mp_wpndmg aug 15")
parse("mp_wpndmg five-seven 15")
parse("mp_wpndmg galil 19")
parse("mp_wpndmg famas 15")
parse("mp_wpndmg g3sg1 20")
parse("mp_wpndmg_z1 g3sg1 35")
parse("mp_wpndmg laser 200")
parse("mp_wpndmg HE 100")
parse("mp_wpndmg airstrike 250")
parse('mp_building_limit "Turret" 10')
parse('mp_building_limit "Gate Field" 30')
parse('mp_building_price "Turret" 8000')
parse('mp_building_price "Gate Field" 500')
parse('mp_building_price "Barricade" 1500')
parse('mp_building_price "Wall I" 1500')
parse('mp_building_price "Wall II" 2000')
parse('mp_building_price "Wall III" 2500')
parse('mp_building_price "Dispenser" 10000')
parse('mp_building_price "Supply" 10000')
parse('mp_building_health "Barricade" 200')
parse('mp_building_health "Wall I" 250')
parse('mp_building_health "Wall II" 350')
parse('mp_building_health "Wall III" 500')
parse('mp_building_health "Turret" 150')
parse('mp_building_health "Gate Field" 1000')
parse('mp_building_health "Dispenser" 500')
parse('mp_building_health "Supply" 500')
parse('mp_building_health "Super Supply" 1000')
parse('mp_building_health "Dual Turret" 200')
parse('mp_building_health "Triple Turret" 250')
